In [6]:
import pandas as pd

In [100]:
data = pd.read_csv('C:\\Users\\Sai\\Desktop\\ML\\Training Data (2).csv')

In [101]:
data.head()

,id,user_id,permno,text,tone
0,6244087,32357,1598,"This cup with handle buy point here of 43.83, ...",Bullish
1,6244091,32357,6829,Nice accumulation recently for this retailer. ...,Bullish
2,6245240,2503,5047,$GE http://stks.co/1jmZ Consolidating after a ...,Bullish
3,6246498,1317,5116,$GNTX http://stks.co/1jxQ Over $30.05,Bullish
4,6247682,32357,4058,"Had some trouble with the 40 wk last week, but...",Bullish

In [102]:
data1 = data.iloc[:,3:5]

In [103]:
import re
#Empty list
text1 = []
#Here we are removing the domain address
url_reg  = r'[a-z]*[:.]+\S+'
for i in data['text']:
     text1.append(re.sub(url_reg, '', i))

In [104]:
#Converting into Data Frame
text1 = pd.DataFrame(text1,columns = ['text1'])

In [105]:
#Concatinatin the two data frames
dataset = pd.concat([data1,text1], axis = 1)
dataset.head()

,text,tone,text1
0,"This cup with handle buy point here of 43.83, ...",Bullish,This cup with handle buy point here of 43 sugg...
1,Nice accumulation recently for this retailer. ...,Bullish,Nice accumulation recently for this retailer. ...
2,$GE http://stks.co/1jmZ Consolidating after a ...,Bullish,$GE Consolidating after a huge run up. A buy ...
3,$GNTX http://stks.co/1jxQ Over $30.05,Bullish,$GNTX Over $30
4,"Had some trouble with the 40 wk last week, but...",Bullish,"Had some trouble with the 40 wk last week, but..."

In [106]:
#Here removing the uncleaned Text column
dataset.drop(['text'],inplace = True,axis =1)

In [107]:
dataset.head()

      tone                                              text1
0  Bullish  This cup with handle buy point here of 43 sugg...
1  Bullish  Nice accumulation recently for this retailer. ...
2  Bullish  $GE  Consolidating after a huge run up. A buy ...
3  Bullish                                    $GNTX  Over $30
4  Bullish  Had some trouble with the 40 wk last week, but...

In [108]:
dataset = dataset[['text1','tone']]

In [109]:
dataset.head()

                                               text1     tone
0  This cup with handle buy point here of 43 sugg...  Bullish
1  Nice accumulation recently for this retailer. ...  Bullish
2  $GE  Consolidating after a huge run up. A buy ...  Bullish
3                                    $GNTX  Over $30  Bullish
4  Had some trouble with the 40 wk last week, but...  Bullish

In [111]:
lower = []
for i in dataset['text1']:
    z = i.lower()
    lower.append(z)

In [118]:
text2 = pd.DataFrame(lower,columns = ['Text'])

In [119]:
text2.head()

                                                Text
0  this cup with handle buy point here of 43 sugg...
1  nice accumulation recently for this retailer. ...
2  $ge  consolidating after a huge run up. a buy ...
3                                    $gntx  over $30
4  had some trouble with the 40 wk last week, but...

In [125]:
dataset1 = pd.concat([dataset,text2], axis = 1)

In [127]:
dataset1.head()

,text1,tone,Text
0,This cup with handle buy point here of 43 sugg...,Bullish,this cup with handle buy point here of 43 sugg...
1,Nice accumulation recently for this retailer. ...,Bullish,nice accumulation recently for this retailer. ...
2,$GE Consolidating after a huge run up. A buy ...,Bullish,$ge consolidating after a huge run up. a buy ...
3,$GNTX Over $30,Bullish,$gntx over $30
4,"Had some trouble with the 40 wk last week, but...",Bullish,"had some trouble with the 40 wk last week, but..."

In [128]:
#Here removing the uncleaned Text column
dataset1.drop(['text1'],inplace = True,axis =1)

In [129]:
dataset1.head()

      tone                                               Text
0  Bullish  this cup with handle buy point here of 43 sugg...
1  Bullish  nice accumulation recently for this retailer. ...
2  Bullish  $ge  consolidating after a huge run up. a buy ...
3  Bullish                                    $gntx  over $30
4  Bullish  had some trouble with the 40 wk last week, but...

In [130]:
dataset1 = dataset1[['Text','tone']]

In [131]:
dataset1.head()

                                                Text     tone
0  this cup with handle buy point here of 43 sugg...  Bullish
1  nice accumulation recently for this retailer. ...  Bullish
2  $ge  consolidating after a huge run up. a buy ...  Bullish
3                                    $gntx  over $30  Bullish
4  had some trouble with the 40 wk last week, but...  Bullish

# We Have done Data Cleaning Part Congo---

# From Here Actual Part starts

In [132]:
dataset1 = dataset1.values

In [133]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [134]:
clf = LabelEncoder()
dataset1[:,1] = clf.fit_transform(dataset1[:,1])

In [142]:
data = pd.DataFrame(dataset1, columns = ['text','tone'])

                                                  text tone
0    this cup with handle buy point here of 43 sugg...    1
1    nice accumulation recently for this retailer. ...    1
2    $ge  consolidating after a huge run up. a buy ...    1
3                                      $gntx  over $30    1
4    had some trouble with the 40 wk last week, but...    1
5    nice tight handle on low volume for this blast...    1
6    $gntx  from watch list over our line on 12% av...    1
7    $ctas  on watch list went over island on thurs...    1
8    has not been on my radar (thin) but one good l...    1
9    $asna  on watch list with 17% ave volume - ran...    1
10   $vz weekly. notice vz has been trading within ...    1
11                                      $gps  over $19    1
12   $asna  from watch list triggered tues ran yest...    1
13             $gps  rough morning, but still bullish.    1
14   knocking on the 200 day door. buy stop through...    1
15   this ones base is getting loose, but that 40 w...    1
16   $syk  motoring through prior resistance nicely...    1
17                     $syk  c to locate demand. nice.    1
18   $tho  stocktwits has $thor handle wrong but he...    1
19               $vz  $vz can push if market will hold    1
20   $ovti  $ovti $foe $immr $mtl $phh $sa cheapo&#...    1
21   $low  $low $yong $swft $sb $nq $asti a few kic...    1
22   $hrs  long with trading plan - explanation si ...    1
23   would like to see the right side build a bit s...    1
24   $tho  i got in early on $thor and dident buy p...    1
25   $alog  freakin gorgeous chart, use the 8 ema a...    1
26   $m  rating cramer&#39;s game plan stocks for w...    1
27   base on base trigger point of 55 as some names...    1
28   $fdx  updated chart. made the move on a gap up...    1
29   $tkr  nice b/o, adx turning up, recent macd po...    1
..                                                 ...  ...
970  should get long $jnj for all the band-aid sale...    0
971  $hpq debt to equity staggering 124 - not feeli...    0
972  $hd put/call curling up from extreme lows look...    0
973  $mat in some $33 and $35 puts, $mat and $has b...    0
974  question to $aapl fanbois: y didnt $goog $ma $...    0
975                   $mat &amp; $has breakdown looms!    0
976  $hott $rth $urbn $rl $m $amzn $sks more on wea...    0
977  $ltd ltd weekly rsi  with retail getting hit, ...    0
978  making 50 day lows in $xly spdr: $fdo $tgt $dr...    0
979  discount retailers are an emerging short oppor...    0
980  sold $aapl $v $kog $aig $fcx. holding a little...    0
981               $hd shorting solidly. next stop: 51     0
982  cliffs this, cliff  that&#39;s all im hearing....    0
983                               $hpq short to 12,50     0
984  wsj: pentagon to warn 800,000 employees in jan...    0
985                       $hpq double down on  12  er     0
986  $low    looking for a pullback on low. seems o...    0
987           $m - been re-building our short position    0
988  right, first thing&#39;s first: $gps, $m and $...    0
989  $m noo, leave some action for the premarket to...    0
990                    $gps wow that wa s a fast fast     0
991                          $m - added to short today    0
992                    $m - about 2/3 of short covered    0
993            $hpq you can only go so high on hot air    0
994  @tradewithmojo fed policy is becoming increasi...    0
995     @2kaykim i see a h&amp;s on daily here bro $hd    0
996                      $m - starting to give up the     0
997  $ko has trouble staying above 200 day sma past...    0
998  @sejd213 guess thats what makes a market i see...    0
999  @sejd213 also ichimuko cloud projecting lower ...    0

[1000 rows x 2 columns]

In [140]:
from textblob import TextBlob

In [143]:
list = []
for i in data.text:
    obj = TextBlob(i)
    list.append(obj)

In [145]:
list[0:5]

[TextBlob("this cup with handle buy point here of 43 suggests economy may be mending $ame "),
 TextBlob("nice accumulation recently for this retailer. cup with handle trigger of 26 $low "),
 TextBlob("$ge  consolidating after a huge run up. a buy if $17 holds."),
 TextBlob("$gntx  over $30"),
 TextBlob("had some trouble with the 40 wk last week, but a buy stop above that line at 59 would be prudent $dov ")]

In [146]:
senti = []
for i in list:
    sentiment = i.sentiment.polarity
    print(sentiment)
    senti.append(sentiment)

0.0
0.19999999999999998
0.4000000000000001
0.0
-0.06666666666666667
0.042857142857142844
0.35
0.16666666666666666
0.3
0.25
0.0
0.0
0.5
-0.1
0.0
-0.20887667887667888
0.3
0.6
-0.5
0.0
0.0
-0.03
-0.05
-0.2571428571428572
0.1
0.7
-0.4
-0.8
0.0
0.28545454545454546
0.0
0.16666666666666666
-0.17857142857142858
-0.4680555555555556
0.019999999999999997
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.025
0.0
0.09999999999999999
0.0
0.6
0.12
-0.8
0.5
0.375
0.42333333333333334
0.0
-0.05
0.0
0.20625
0.125
0.3
-0.8
0.2857142857142857
0.0
0.0
-0.2260416666666667
0.35
0.18
0.6
0.05
0.7
0.0
-0.8
-0.8
0.0
0.0
0.7
0.0
0.26666666666666666
0.78
-0.075
0.0
0.027142857142857146
0.0
0.35
0.35
-0.024999999999999998
-0.6999999999999998
-0.02619047619047619
0.16666666666666666
0.0
0.0
0.0
-0.05952380952380953
0.0
0.31666666666666665
0.0
0.35
0.13636363636363635
0.55
0.028571428571428543
0.0
0.4666666666666666
-0.35833333333333334
-0.3333333333333333
0.0
0.0
0.06818181818181818
0.17380952380952377
0.0
0.0
0.1
0.12857142857142856
0.13333333333333333
0.0
0.09999999999999998
0.0
0.7
-0.8
-0.13333333333333333
-0.016666666666666666
0.0
0.12777777777777777
0.0
0.0
0.0
0.0
0.05333333333333334
0.75
0.08333333333333334
-0.05
0.25
0.85
0.0
-0.08928571428571429
0.0
0.0
0.0
0.0
0.03333333333333333
0.3
0.0
0.30000000000000004
0.5
0.16666666666666666
0.0
0.6
0.35
0.0
0.7
0.36818181818181817
0.0
0.7
0.25
-0.2916666666666667
0.175
0.0
-0.09375
0.011538461538461539
-0.10937500000000001
0.6
0.325
0.05
0.0
0.5166666666666666
0.0
0.2607142857142857
0.0
0.25
0.06666666666666667
0.6
0.6
0.0
0.45833333333333337
0.0
0.0
0.13035714285714284
0.13333333333333333
0.0
-0.05
0.21666666666666665
0.19593939393939394
0.2
0.05
0.0
0.0
0.020833333333333332
-0.009285714285714286
0.0
0.0
0.0
0.0
0.08333333333333333
0.5
0.3
0.0
0.08333333333333333
0.0
0.0
0.6
0.20000000000000004
0.19999999999999996
0.0
0.6499999999999999
-0.05
-0.025
0.0
-0.8
-0.05
0.0
0.0
-0.23
0.5
0.0
0.6
0.6
0.1
0.0
0.5
0.0
0.21666666666666665
0.0
0.0
0.8
0.0
0.0
0.11249999999999999
0.3
0.0
0.13636363636363635
0.64
0.6666666666666666
-0.42500000000000004
0.5
0.024999999999999967
0.0
-0.1
1.0
0.8
0.0
0.7
0.0
0.0
-0.2916666666666667
0.35
0.3
0.25
0.16
0.03194444444444443
0.25
0.4333333333333333
-0.025
0.0
-0.125
0.3
0.1
-0.05
0.0
0.39999999999999997
0.0
0.0
-0.1851851851851852
0.21666666666666665
0.1481818181818182
0.0
0.0
0.0
0.0
0.0
0.2816666666666667
0.14
-0.016666666666666666
0.0
0.0
0.21103896103896103
0.0
0.09999999999999999
0.05
0.3
0.1481818181818182
-0.05
0.0
0.6
0.09999999999999999
0.07499999999999998
0.0
0.0
0.0
0.8
0.0
0.8
0.13791666666666666
-0.125
0.0
-0.011111111111111118
0.33
-0.41250000000000003
-0.10000000000000003
0.0
0.4
0.16666666666666663
0.0
0.0
-0.05
0.1321212121212121
0.0
0.22727272727272727
0.0
0.0
0.11249999999999999
0.10833333333333332
-0.15555555555555559
0.0
0.0
0.0
0.16
0.55
0.09444444444444444
0.0
0.0
-0.05
0.0
0.2333333333333333
0.32499999999999996
-0.1027777777777778
0.0
0.0
0.16545454545454547
-0.039285714285714285
0.21666666666666665
0.06818181818181818
-0.22499999999999998
0.13636363636363635
0.0
-0.0625
0.0
0.13636363636363635
0.0
0.0
0.024999999999999994
0.05
0.35
0.0
0.0
0.0
0.46875
0.0
-0.125
0.6
0.41111111111111115
0.0
0.375
0.25
-0.06666666666666667
0.25
0.35
-0.07954545454545454
0.0
0.015625000000000007
0.8
0.13636363636363635
-0.125
0.2333333333333333
0.2125
0.6
0.13636363636363635
0.0
0.0
0.0
0.24909090909090909
0.85
0.13636363636363635
0.0
-0.5
0.0
0.06818181818181818
0.09999999999999999
0.0
0.016666666666666673
0.2333333333333333
-0.004761904761904782
0.0
0.005681818181818177
0.0
0.4
0.0
2.7755575615628914e-17
0.25
0.12777777777777777
0.0
0.0
0.6
0.0
0.5
0.0
0.0
0.0
0.0
0.0
0.1714285714285714
-0.05
0.2
0.0
0.0
-0.125
0.75
0.0
0.2193181818181818
0.0
0.5
0.7
0.5
0.3666666666666667
0.0
0.0
0.0
0.0
0.7
0.0
0.3333333333333333
0.6000000000000001
0.25
0.7
0.0
0.0
0.0
0.0
0.35000000000000003
0.0
-0.75
0.0
0.5
0.0
-0.16999999999999998
0.13636363636363635
0.0
0.425
0.0
0.0
0.0
0.0
0.0
0.0
-0.05
0.4
0.5
0.10000000000000002
0.0
0.09999999999999999
-0.2125
0.0
0.0
-0.05
0.21666666666666665
0.2333333333333333
0.0
-0.13888888888888887
0.6
0.0
0.0
0.0
0.0
0.3533333333333333
0.0
0.08
0.0
0.125
0.0
-0.05
0.0
-0.016666666666666666
0.2
0.0
0.4
0.0
0.0
0.5
0.0
0.0
0.2
0.1
0.3416666666666667
-0.18333333333333338
0.0
0.5
0.0
0.25
-0.05
0.17083333333333334
0.0
0.0
0.35
-0.025
0.1
0.2
0.0
0.0
0.0
0.315625
0.3333333333333333
0.41666666666666663
-0.011111111111111117
-0.25
0.0
0.0
0.0
0.0
-0.24375000000000002
0.0
0.0
0.1481818181818182
0.0
0.0
0.0
-0.4000000000000001
-0.2
0.0
-0.05
-0.021875000000000006
0.3333333333333333
0.18666666666666665
0.0
0.25
0.4
0.25
0.35
0.0
-0.15555555555555559
0.0
-0.255
0.35
0.048611111111111105
-0.04999999999999999
0.0
-0.5
0.0
0.0
0.06666666666666667
-0.15555555555555559
0.3
0.0
0.0
0.5
0.0
-0.175
0.0
0.0
0.27142857142857146
0.0625
0.0
0.20000000000000004
0.44999999999999996
0.1
0.2
0.14285714285714285
-0.15555555555555559
0.0
0.0
0.0
1.0
-0.2
0.0
0.0
0.0
0.0
0.21666666666666665
-0.05
0.4375
0.0
0.0
0.0
-0.15555555555555559
0.3
0.0
0.35
0.0
0.0
0.0
0.5
0.0
0.0
0.26666666666666666
0.25
0.19999999999999998
0.9765625
0.0
0.2
-0.05
0.0
0.0
0.0
-1.0
0.12333333333333335
0.0
0.0
0.0
0.0
0.06818181818181818
0.0
0.0
0.06666666666666667
0.0
0.0
0.31523809523809526
0.7
0.0
0.25
-0.2916666666666667
0.0
0.5
-0.07777777777777779
0.11481481481481481
-0.1388888888888889
0.057499999999999996
0.1953125
0.0
0.1361111111111111
0.0
0.0
0.0
0.0
0.0
0.25
0.25
0.0
0.0
0.25
0.0
0.0
0.5
0.25
0.0
0.0
0.0
0.0
0.35
-0.45
0.0
0.10833333333333334
0.0
0.0
0.35
0.1
0.16545454545454547
0.0
0.0
0.0
0.0
-0.2
-0.6
0.35
0.0
0.0
-0.35
0.0
0.35
0.0
0.0
0.65
0.06818181818181818
0.0
0.0
-0.2
0.165
0.0
-0.2777777777777778
-0.0625
0.25
0.0
0.0
0.06666666666666667
-0.32499999999999996
0.5
0.0
0.0
-0.375
-0.1
0.5
0.05
-0.1
0.8
0.32500000000000007
-0.15555555555555559
-0.45
-0.0625
0.0
0.09999999999999999
0.0
0.0
0.0
-0.15555555555555559
1.0
0.17380952380952377
0.48750000000000004
0.08611111111111112
0.36028571428571426
-0.3038194444444445
0.0
0.0
0.0
0.4333333333333333
-0.05
-0.15555555555555559
0.15
0.07888888888888891
0.1
0.09583333333333333
0.13636363636363635
0.0
-0.01666666666666668
0.13333333333333333
0.4
0.06666666666666665
-0.05714285714285716
-0.03571428571428571
0.0
-0.2
0.07500000000000001
0.04999999999999999
0.0
0.16500000000000004
0.05
-0.1606060606060606
-0.07566137566137567
0.0
0.0
0.0
-0.023809523809523808
-0.07685185185185188
0.4
0.16
0.0
0.875
-0.5
-0.08928571428571427
-0.03148148148148149
-0.17857142857142858
0.45499999999999996
0.0
0.0
-0.15
-0.08333333333333333
0.0
0.029365079365079344
0.625
0.0
0.06102693602693601
-0.3888888888888889
0.0
0.5
-0.15555555555555559
0.06666666666666667
0.0
0.4
0.009523809523809526
0.05
0.4
0.0
0.0
0.0946031746031746
0.11363636363636363
0.0
0.0
0.3125
-0.6999999999999998
0.0
0.0
0.0
0.14814814814814814
0.22380952380952382
0.0
0.0
-0.0625
0.0
0.375
-0.15555555555555559
-0.0625
0.0
0.11666666666666665
0.25
0.0
-0.05
0.06666666666666667
-0.4333333333333333
-0.011111111111111117
-0.07777777777777779
0.0
-0.15
0.25
0.0
0.05
0.35
0.0
0.2
0.11818181818181818
-0.1
0.04545454545454545
0.11249999999999999
-0.19047619047619047
0.0
0.0625
0.0
0.8
0.4000000000000001
0.0
0.0
-0.5
0.2833333333333334
0.19814814814814816
-0.075
0.0
0.0
0.7500000000000001
0.0
-0.14027777777777778
0.21428571428571427
0.0
-0.15555555555555559
0.0
-0.15555555555555559
0.25
0.3481481481481481
0.0
0.0
0.0
0.0
0.0
0.0
-0.11666666666666665
0.39
0.0
-0.051851851851851864
0.0
0.0
0.1
0.0
-0.03333333333333335
0.0
-0.038888888888888896
0.0
0.0
0.0
-0.07142857142857142
0.45
0.0
-0.04646464646464646
0.07142857142857142
-0.5
-0.09999999999999999
0.0
0.0
0.0
0.0
-0.25
-0.2277777777777778
0.0
0.21212121212121213
0.0
0.0
0.0
-0.07142857142857142
0.0
0.0
0.0
0.2
-0.08333333333333333
0.25
0.35
0.15
0.0
-0.5357142857142857
0.35
-0.25
0.0
0.0
0.2333333333333333
0.4222222222222222
-0.16666666666666666
0.0
-0.4
0.06666666666666667
0.13333333333333333
-0.06785714285714287
0.0
0.24545454545454545
0.6
0.5
0.124
0.0
-0.07142857142857142
0.25
0.0
0.0
0.07083333333333335
0.3
0.0
0.0
0.0
0.0
0.4333333333333333
0.0
-0.1134920634920635
0.21666666666666667
0.0
0.0
0.25
0.0
-0.05
0.43333333333333335
0.10952380952380954
0.0
0.0
-0.07142857142857142
0.0
-0.07777777777777779
-0.05
0.21666666666666665
0.0
-0.025
0.0
0.5785714285714286
-0.8
-0.25
0.0
-0.475
-0.0625
0.0
0.0
-0.13333333333333333
0.0
-0.018750000000000003
-0.2363095238095238
0.0
-0.15555555555555559
-1.0
-0.175
0.05
0.0
0.0
0.0
-0.02500000000000001
0.0
0.22749999999999998
0.0
0.0
0.0
-0.175
0.0
0.0
0.0
0.0
0.5
0.0
0.13636363636363635
0.0
0.0
-0.07777777777777779
0.0
-0.041666666666666664
0.0
0.0
0.4
0.0
0.5
0.625
0.014814814814814808
0.014814814814814808
0.0
0.4
0.0
-0.04375
-0.1875
-0.42500000000000004
0.0
-0.125
0.0
0.0
0.0
0.0625
0.4
0.0
0.0
-0.1875
0.0
0.0
0.0
0.0
-0.07777777777777779
0.07142857142857142
0.0
0.2619047619047619
-0.06851851851851852
0.16666666666666666
0.0
0.0
0.1366666666666667
0.016666666666666663
0.0
0.0
-0.05714285714285715
0.5
0.5

In [148]:
sentiment = pd.DataFrame(senti,columns = ['sentiment'])

In [149]:
sentiment.head()

   sentiment
0   0.000000
1   0.200000
2   0.400000
3   0.000000
4  -0.066667

In [151]:
df = pd.concat([data,sentiment],axis = 1)

In [160]:
senti = []
for i in df.sentiment:
    if i > 0.4:
        senti.append('positive')
    else:
        senti.append('negative')

In [5]:
sentim = pd.DataFrame(senti,columns = ['sentiment_text'])

NameError: name 'pd' is not defined

In [4]:
final_data = pd.concat([df,sentim],axis = 1)

NameError: name 'pd' is not defined

In [3]:
final_data

NameError: name 'final_data' is not defined